### ISSUE TITLE
Allow passing a value with spaces without wrapping it as an escaped string

### ISSUE THREAD

**Issue by demoive** [borodean/less-properties#5]
With any value that has spaces in it (e.g. `1px solid red`), fails to generate a proper CSS definition since LESS treats the argument as an array of values. You can get around this in your solution by passing it in as an escaped string (e.g. `~"1px solid red"`). Out of your test cases, the following seem to contain this bug:

```
.test-compound
.test-function-param-preserve-second
.test-function-param-preserve-first
.test-function-param-preserve-double
.test-nested-coumpoun
```

Here is an example of the failing output:

``` css
.property(transition, all .5s ease, "webkit moz o");

.test-compound {
  -test-should: generate a property definition that looks correct;
  -less-property: ;
  -webkit-transition: [all, 0.5s, ease];
  -moz-transition: [all, 0.5s, ease];
  -o-transition: [all, 0.5s, ease];
  transition: [all, 0.5s, ease];
}
```

In [my solution](https://gist.github.com/demoive/5641752), I encountered this same problem, but resolved it by escaping the argument before using it. In your mixin, if you escape both the `@property` and `@value` arguments into new variables, I think it would be more robust. For example:

``` css
.property(@property, @value, @prefixes: '', @base: true) {
  @prop: e('@{property}');
  @vals: e('{@value}');

  // ...
}
```
